import Head from 'next/head'
import type { NextPage } from 'next'

export default function Home() {
  return (
    <>
      <Head>
        <title>Organize.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2 className='flex w-full items-center justify-center text-2xl'>Hello Next</h2>
      </main>
    </>
  )
}
